ALTER TABLE images
MODIFY COLUMN user_id BIGINT,
MODIFY COLUMN webformat_url LONGTEXT NOT NULL,
MODIFY COLUMN large_image_url LONGTEXT,
MODIFY COLUMN preview_url LONGTEXT,
MODIFY COLUMN image_url LONGTEXT,
MODIFY COLUMN fullhd_url LONGTEXT;
